run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - unused
    - lll

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
