name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v3
        with:
          repository: takealook97/homebrew-sshift
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Calculate SHA256
        id: sha256
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          SOURCE_URL="https://github.com/takealook97/sshift/archive/refs/tags/${VERSION}.tar.gz"
          SHA256=$(curl -sL "$SOURCE_URL" | shasum -a 256 | cut -d' ' -f1)
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Update Formula
        run: |
          cd homebrew-tap
          sed -i "s/version \".*\"/version \"${{ steps.sha256.outputs.version }}\"/" sshift.rb
          sed -i "s/sha256 \".*\"/sha256 \"${{ steps.sha256.outputs.sha256 }}\"/" sshift.rb
          sed -i "s|url \".*\"|url \"https://github.com/takealook97/sshift/archive/refs/tags/${{ github.ref_name }}.tar.gz\"|" sshift.rb

      - name: Commit and push
        run: |
          cd homebrew-tap
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sshift.rb
          git commit -m "Update sshift to ${{ steps.sha256.outputs.version }}"
          git push
